spring.application.name=spring-security-demo
spring.security.user.name=kevin
spring.security.user.password=0301

server.servlet.session.cookie.same-site=strict

spring.data.redis.url=jdbc:postgresql://localhost:5433/kevin
spring.datasource.username=postgres
spring.datasource.password=0301
spring.datasource.driver-class-name=org.postgresql.Driver